### ISSUE TITLE
Broken: `experiments/configs/profiled_runs.py` references non-existent config

### ISSUE THREAD

**Issue by scottcanoe** [thousandbrainsproject/monty_lab#1]
Attempting to run configs under `experiments/configs` will trigger an exception due to an issue with `profiled_runs.py`. 

```shell
(monty_lab) ➜  experiments git:(main) python run.py -e some_experiment
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    from configs import CONFIGS
  File "/Users/sknudstrup/tbp/monty_lab/experiments/configs/__init__.py", line 19, in <module>
    from .profiled_runs import CONFIGS as PROFILED_RUNS
  File "/Users/sknudstrup/tbp/monty_lab/experiments/configs/profiled_runs.py", line 31, in <module>
    supervised_pre_training_storeall = import_config_from_monty(
  File "/Users/sknudstrup/tbp/monty_lab/experiments/configs/config_utils.py", line 21, in import_config_from_monty
    return getattr(module, config_name)
AttributeError: module 'pretraining_experiments.py' has no attribute 'supervised_pre_training_storeall'
```

`supervised_pre_training_storeall` no longer exists in `pretraining_experiments.py`. I can replace it with an existing config if I know what to replace it with. Maybe `only_surf_agent_training_allobj`?

**Comment by scottcanoe** [comment]
Fix merged [here](https://github.com/thousandbrainsproject/monty_lab/pull/2).
